import type { Metadata } from 'next';
import { faqPageSchema } from '@/lib/schema';
import JsonLd from '@/components/JsonLd';
import FAQ from '@/components/FAQ';

export const metadata: Metadata = {
  title: 'FAQ',
  description: 'Frequently asked questions about Lunarium — release date, price, platforms, gameplay mechanics, system requirements, endings, and more.',
};

const FAQ_ITEMS = [
  { question: 'What is Lunarium?', answer: 'Lunarium is a hand-drawn isometric action RPG developed by Lunarium Game Studio, a nine-person debut team based in Shanghai, and published by Imperfect Games. You play as Ave, a light-armored swordmaster, alongside Lune, a mysterious Starfarer sorceress who acts as an AI companion.' },
  { question: 'When does Lunarium release?', answer: 'Lunarium launches on July 29, 2026 on Steam for PC, priced at $17.99 USD.' },
  { question: 'What platforms is Lunarium on?', answer: 'PC via Steam at launch. Console versions (PlayStation, Xbox, Switch) have not been announced but may follow based on sales performance.' },
  { question: 'Is Lunarium a soulslike?', answer: 'Not exactly. While it shares some DNA — parry-primary combat, bench save points, limited healing — the developers have emphasized that the difficulty is designed to teach rather than punish. The tone is intimate and relationship-focused.' },
  { question: 'Can I play as Lune?', answer: 'You control Ave directly in combat. Lune operates as an AI-controlled companion who supports in combat and exploration. You can upgrade Lune\'s skills, direct her with D-pad commands, and unlock her ultimate abilities.' },
  { question: 'How does the Resonance Points system work?', answer: 'Resonance Points are a shared resource generated by Ave and Lune fighting together. Generate RP through successful parries, combos, and defeating enemies. Spend RP on powerful coordinated attacks, emergency healing, and ultimate abilities.' },
  { question: 'How long is Lunarium?', answer: 'A first playthrough takes approximately 12-18 hours depending on exploration and difficulty. Completionist runs (all items, both endings) take 25-30 hours.' },
  { question: 'How many endings does Lunarium have?', answer: 'Three endings: Ending A (Star\'s Return), Ending B (Together), and a hidden True Ending (Shared Light). The True Ending requires meeting specific conditions throughout the game.' },
  { question: 'Is there multiplayer or co-op?', answer: 'No. Lunarium is a single-player experience focused on the relationship between Ave and Lune.' },
  { question: 'Can I respec my skills?', answer: 'Yes. Respeccing is available at any Temple save point. Your first respec is free; subsequent respecs cost Stardust.' },
  { question: 'Is there a New Game Plus?', answer: 'Yes. After completing any ending, NG+ unlocks with carried-over charms, cloaks, and Stardust. Character levels and story progress reset. Harder enemy variants appear.' },
  { question: 'What are the PC system requirements?', answer: 'Minimum: Windows 10, Intel i5 Quad-Core 2.7 GHz, 8 GB RAM, GTX 660 / RX 460, 5 GB storage. Recommended: Windows 10/11, Intel i7, 16 GB RAM, GTX 1060 / RX 580, 5 GB SSD.' },
  { question: 'Does Lunarium support controller?', answer: 'Yes. Full controller support for Xbox, PlayStation, and generic controllers.' },
  { question: 'What languages are supported?', answer: 'English, Japanese, Traditional Chinese, and Simplified Chinese (interface and subtitles).' },
  { question: 'Is there a demo?', answer: 'A demo was available during the March 2026 preview period covering the first two chapters. Check the Steam page for current demo availability.' },
];

export default function FAQPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <JsonLd data={faqPageSchema(FAQ_ITEMS)} />
      <h1 className="text-3xl md:text-4xl font-bold text-white mb-2">Frequently Asked Questions</h1>
      <p className="text-gray-400 mb-8">Common questions about Lunarium — gameplay, characters, endings, and more.</p>
      <FAQ items={FAQ_ITEMS} />
    </div>
  );
}
