import Link from 'next/link';
import { faqPageSchema, videoGameSchema } from '@/lib/schema';
import JsonLd from '@/components/JsonLd';
import GuideCard from '@/components/GuideCard';

const FEATURED_GUIDES = [
  { title: 'Beginner Guide — Getting Started in Lunarium', description: 'New to Lunarium? Learn the basics — controls, combat fundamentals, character introductions, and the first hour of gameplay.', slug: 'beginner-guide', category: 'Beginner', updated: '2026-07-25' },
  { title: 'Combat Guide — Parry, Dodge & Resonance System', description: 'Master Lunarium\'s combat: perfect parry timing, dodge mechanics, and the Resonance Points system for coordinated attacks.', slug: 'combat-guide', category: 'Combat', updated: '2026-07-25' },
  { title: 'Ave Build Guide — Best Swordmaster Builds', description: 'Optimized builds for Ave covering skill tree paths, best equipment, charm setups, and playstyle strategies.', slug: 'ave-build-guide', category: 'Builds', updated: '2026-07-25' },
  { title: 'Lune Guide — Starfarer Abilities & Synergy', description: 'Complete guide to Lune\'s Starfarer abilities, AI companion behavior, synergy combos with Ave, and support tactics.', slug: 'lune-guide', category: 'Characters', updated: '2026-07-25' },
  { title: 'Skill Tree Guide — All Skills & Best Upgrades', description: 'Full breakdown of Ave and Lune\'s skill trees. Best upgrade paths, priority skills, and respec strategy.', slug: 'skill-tree-guide', category: 'Progression', updated: '2026-07-25' },
  { title: 'Boss Guide — All Bosses & Strategies', description: 'Every boss in Lunarium with attack patterns, parry windows, recommended builds, and rewards for each encounter.', slug: 'boss-guide', category: 'Bosses', updated: '2026-07-25' },
];

const FAQ_ITEMS = [
  { question: 'What is Lunarium?', answer: 'Lunarium is a hand-drawn isometric action RPG developed by Lunarium Game Studio. You play as Ave, a light-armored swordmaster, alongside Lune, a mysterious Starfarer sorceress who acts as an AI companion. The game features parry-based combat, skill trees, equipment upgrades, and a story with two distinct endings.' },
  { question: 'When does Lunarium release?', answer: 'Lunarium launches on Steam for PC on July 29, 2026, priced at $17.99 USD. It supports English, Japanese, Traditional Chinese, and Simplified Chinese.' },
  { question: 'Can I play as both Ave and Lune?', answer: 'You control Ave directly in combat — she wields a sword and relies on precise parries and dodges. Lune operates as an AI-controlled companion who supports in combat and exploration. You can upgrade both characters\' skill trees.' },
  { question: 'How does the Resonance Points system work?', answer: 'Resonance Points are a shared resource generated by Ave and Lune fighting together. Spend Resonance Points to unleash powerful coordinated attacks, weaken enemies, and trigger special combo abilities.' },
  { question: 'How many endings does Lunarium have?', answer: 'Lunarium has two distinct endings. Your choices throughout the game and which character you strengthen your bond with will determine which ending you see. Check our Endings Guide for details.' },
  { question: 'Is there a New Game Plus mode?', answer: 'Information about New Game Plus will be confirmed at launch. Based on previews, the game is designed for replayability with different build choices and both endings to discover.' },
];

export default function Home() {
  return (
    <>
      <JsonLd data={videoGameSchema()} />
      <JsonLd data={faqPageSchema(FAQ_ITEMS)} />
      <section className="relative py-20 md:py-28 px-4 text-center bg-gradient-to-b from-[#1a1a2e] to-[#0f0f23]">
        <h1 className="text-4xl md:text-5xl font-bold text-white mb-4 tracking-tight">Lunarium <span className="text-amber-400">Wiki</span></h1>
        <p className="text-lg text-gray-400 max-w-xl mx-auto mb-2">Complete guide hub for the hand-drawn action RPG — combat, builds, bosses, walkthroughs, and endings.</p>
        <p className="text-sm text-gray-600 mb-8">Launching July 29, 2026 on Steam · $17.99</p>
        <div className="flex items-center justify-center gap-4">
          <a href="https://store.steampowered.com/app/2939790/Lunarium/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 bg-amber-500 hover:bg-amber-400 text-black font-semibold px-6 py-3 rounded-lg transition-colors text-sm">Wishlist on Steam</a>
          <Link href="/guides/beginner-guide" className="inline-flex items-center gap-2 border border-gray-600 hover:border-amber-500 text-gray-300 hover:text-amber-400 px-6 py-3 rounded-lg transition-colors text-sm">Start with Beginner Guide →</Link>
        </div>
      </section>
      <section className="max-w-6xl mx-auto px-4 py-16">
        <h2 className="text-2xl font-bold text-white mb-8">Start Here</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {FEATURED_GUIDES.map((g) => (<GuideCard key={g.slug} {...g} />))}
        </div>
        <div className="text-center mt-8"><Link href="/guides" className="text-amber-400 hover:text-amber-300 text-sm font-medium transition-colors">View All Guides →</Link></div>
      </section>
      <section className="max-w-3xl mx-auto px-4 py-16 border-t border-[#1a1a2e]">
        <h2 className="text-2xl font-bold text-white mb-8 text-center">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {FAQ_ITEMS.map((item) => (<details key={item.question} className="group bg-[#1a1a2e] rounded-lg border border-[#2a2a5e]"><summary className="px-5 py-4 cursor-pointer text-white font-medium text-sm hover:text-amber-400 transition-colors select-none">{item.question}</summary><div className="px-5 pb-4 text-gray-400 text-sm leading-relaxed">{item.answer}</div></details>))}
        </div>
      </section>
    </>
  );
}
